/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/reserve': typeof ReserveRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/reserve': typeof ReserveRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/reserve': typeof ReserveRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/gallery'
    | '/menu'
    | '/order'
    | '/reserve'
    | '/story'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/gallery' | '/menu' | '/order' | '/reserve' | '/story'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/gallery'
    | '/menu'
    | '/order'
    | '/reserve'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  OrderRoute: typeof OrderRoute
  ReserveRoute: typeof ReserveRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  OrderRoute: OrderRoute,
  ReserveRoute: ReserveRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
